apiVersion: batch/v1
kind: Job
metadata:
  generateName: dummy-error-handle-
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-1" 
spec:
  template:
    spec:
      containers:
      - name: dummy-message
        image: alpine
        command:
          - "false"
      restartPolicy: Never
  backoffLimit: 2    
