apiVersion: batch/v1
kind: Job
metadata:
  generateName: dummy-slack-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: dummy-run
        image: alpine
        command:
          - "echo"
          - "finished"
      restartPolicy: Never
  backoffLimit: 2    
