apiVersion: batch/v1
kind: Job
metadata:
  generateName: dummy-sync-fail-
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "5" 
spec:
  template:
    spec:
      containers:
      - name: dummy-sync-fail
        image: alpine
        command:
          - "exit"
          - "1"
      restartPolicy: Never
  backoffLimit: 2    
