apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "demo-ing"
spec:
  rules:
  - http:
      paths:
      - path: /loan/
        pathType: Prefix
        backend:
          service:
            name: loan
            port:
              number: 8080              