apiVersion: v1
kind: Service
metadata:
  name: interest
  annotations:
    argocd.argoproj.io/sync-wave: "2"  
spec:
  type: ClusterIP
  selector:
    app: interest
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080